name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install deps
        run: npm ci
      - name: Lint affected
        run: npm run lint
      - name: Test and coverage affected
        run: npm run test:coverage
      - name: Report coverage
        uses: coverallsapp/github-action@v2
        with:
          debug: true
      - name: Build affected
        run: npx nx affected -t build
